### ISSUE TITLE
Cannot call function hasError from auth/register.edge view

### ISSUE THREAD

**Issue by sonika452** [creatrixity/adonis-auth-scaffold#11]

**Comment by creatrixity** [comment]
Please give additional information on the error.

**Comment by sonika452** [comment]
when I am trying to register to page , it's coming an error as "Cannot call function hasError from auth/register.edge view"

**Comment by creatrixity** [comment]
Please ensure the session middleware is correctly added.

**Comment by ogbiyoyosky** [comment]
@sonika452  Make sure you add the argument session on your controller, and check for the middle-ware if its  registered
