### ISSUE TITLE
Invalid "For HTTP" routes after adonis make:auth

### ISSUE THREAD

**Issue by seccomiro** [creatrixity/adonis-auth-scaffold#12]
I'm trying to generate the auth resources using the "For HTTP" option of `adonis make:auth` and it generates the wrong route file inside my project. Instead of creating a file named `authRoutes.js`, it creates a file named `apiAuthRoutes.js`, with api-valid routes.

The problem occurs even if I run `adonis make:auth --http-only`.

The entry at `routes.js` is OK:

```javascript
require('./authRoutes.js');
```

But it will throw an error during the app startup.

BTW: I loved the purpose of the repo and would like to contribute with some PRs in the near future. I have some good ideias. The AdonisJS community needs something like this.

**Comment by creatrixity** [comment]
You could make a pull request and I'd be happy to merge it. I'll fix this issue ASAP.

**Comment by creatrixity** [comment]
Thanks for the kind words. We grow the community faster when we contribute more.
