### ISSUE TITLE
Wrong controller folder for AuthController

### ISSUE THREAD

**Issue by seccomiro** [creatrixity/adonis-auth-scaffold#13]
The `adonis make:auth` generator is creating the `AuthController.js` file inside the `app/Controllers/HTTP` folder.

It needs to be inside `app/Controllers/Http`.

Maybe its related to the AdonisJS version. I'm using 5.0.13.

**Comment by creatrixity** [comment]
I'm aware of this issue as it's particularly a pain for Unix users.

#14 fixes this.

**Comment by seccomiro** [comment]
I think this Issue can be marked as solved.
