### ISSUE TITLE
Is mail sending really working?

### ISSUE THREAD

**Issue by seccomiro** [creatrixity/adonis-auth-scaffold#18]
While trying to test the email templates I realized that, even there are event listeners registered with proper mail sending code, the emails were't send.

Looking through the code I couldn't find any `Event.fire` for them.

Is email sending a work in progress or am I doing something wrong?

**Comment by seccomiro** [comment]
Yeah. I've got it. Adonis Persona will trigger the events.

But the problem is that `authEvents.js` isn't being considered by Adonis at startup.

Apparently the file MUST be called `events.js`. We need to put our events inside of it or we can `require('./authEvents');`.

**Comment by creatrixity** [comment]
Mail sending is an Adonis Persona issue. I have encountered it before and my workaround was to maintain a private Persona fork with a callback instead of an emitted event.

**Comment by creatrixity** [comment]
You may create an issue over at the [Persona issue tracker](https://github.com/adonisjs/adonis-persona/issues)
