### ISSUE TITLE
Cannot call function old from auth/register.edge view

### ISSUE THREAD

**Issue by tinamrak** [creatrixity/adonis-auth-scaffold#5]
I have a fresh Adonis install `adonis new projectname --api` and I get the following error when going to "http://localhost:3333/register":

`Cannot call function old from auth/register.edge view` 

Can you help me out here?

I'm new to Node.js and Adonis so there's a chance that I'm doing something wrong.

**Comment by creatrixity** [comment]
Hi Tina Mrak,

Please make sure you are on a version of Adonis greater than 4.1.0 and you have the Adonis session provider listed in the providers array at `start/app.js`.

Do let us now if you encounter any more problems.

**Comment by tinamrak** [comment]
I think this was it, thank you. I should have left out the --api at the end of "adonis new".

Now, when I try to register a user, I get this error:
`insert into 'users' ('account_status', 'created_at', 'email', 'password', 'updated_at', 'username') values ('pending', '2019-01-31 13:48:47', 'me@example.com', '$2a$10$7KRIPnbPDMGqsGUuB3YeUe.U8rDhL8JnzwYJaJbOdDrv/LSeFcNzO', '2019-01-31 13:48:47', 'tina') - ER_BAD_FIELD_ERROR: Unknown column 'account_status' in 'field list'`

I ran the migration but this field (account_status) is still missing.

**Comment by creatrixity** [comment]
That error comes up because the `account_status` column was not created and is missing in your user migration. Please add this line to the `this.create` closure in `database/migrations/xxxxxxxx_user.js` to create the column.

 ```js
table.boolean('account_status').notNullable()
```

Then run `adonis migration:refresh` to create the column.

**Comment by tinamrak** [comment]
This is it. Thank you Caleb.

**Comment by creatrixity** [comment]
You're welcome, Tina.
