### ISSUE TITLE
Update devDependencies

### ISSUE THREAD

**Issue by Maxximus007** [creatrixity/adonis-auth-scaffold#9]
Hi, Really like your package, but currently npm is screaming vulnerabilities ;).
Can you please update the devDependencies to get rid of these vulnerabilities found in some helper packages?

Not sure these version jumps in these packages will give other issues though..
 
`  "devDependencies": {
    "@adonisjs/ace": "^5.0.0",
    "@adonisjs/fold": "^4.0.5"
  },`
to:
`  "devDependencies": {
    "@adonisjs/ace": "^6.0.0",
    "@adonisjs/fold": "^6.0.3"
  },`

**Comment by creatrixity** [comment]
I'll make a pull to solve this.

**Comment by creatrixity** [comment]
Dev dependencies have been updated.

**Comment by Maxximus007** [comment]
Great! Sorry for not mentioning it before, but there is a dependency for `"adonis-fold": "^3.0.3"`, and it seems that this package is the one giving security warnings.
This package is now non-existent, and probably replaced by `"@adonisjs/fold": "^6.0.3"`.
